backend:
  name: github
  repo: moritzpflueger/fairdentity
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
logo_url: https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/90f458e7-38ac-4132-bb32-0aff816f891b/pegasus-41-strassenlaufschuh-fur-RFt1g4.png

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }